#pragma once
#include "frost_c.h"
#include "Call_types.h"
typedef struct frost$collections$CollectionView frost$collections$CollectionView;
typedef struct org$frostlang$frostc$Compiler org$frostlang$frostc$Compiler;
typedef struct org$frostlang$frostc$ASTNode org$frostlang$frostc$ASTNode;
typedef struct org$frostlang$frostc$FixedArray org$frostlang$frostc$FixedArray;
typedef struct org$frostlang$frostc$Pair org$frostlang$frostc$Pair;
typedef struct frost$collections$ListView frost$collections$ListView;
typedef struct org$frostlang$frostc$Compiler$TypeContext org$frostlang$frostc$Compiler$TypeContext;
typedef struct org$frostlang$frostc$Type org$frostlang$frostc$Type;
#include "org/frostlang/frostc/Position_types.h"
typedef struct org$frostlang$frostc$IR$Value org$frostlang$frostc$IR$Value;
typedef struct org$frostlang$frostc$MethodRef org$frostlang$frostc$MethodRef;
#include "org/frostlang/frostc/expression/Binary/Operator_types.h"
typedef struct org$frostlang$frostc$MethodDecl org$frostlang$frostc$MethodDecl;
typedef struct frost$collections$HashMap frost$collections$HashMap;
#include "org/frostlang/frostc/expression/Call/ImplicationsResult_types.h"
#include "frost/core/Int_types.h"
typedef struct frost$core$String frost$core$String;
#include "frost/core/Bit_types.h"
typedef struct org$frostlang$frostc$expression$Call org$frostlang$frostc$expression$Call;

frost$collections$CollectionView* org$frostlang$frostc$expression$Call$possibleTypes$org$frostlang$frostc$Compiler$org$frostlang$frostc$ASTNode$org$frostlang$frostc$FixedArray$LTorg$frostlang$frostc$ASTNode$GT$R$frost$collections$CollectionView$LTorg$frostlang$frostc$Type$GT$Q(org$frostlang$frostc$Compiler* p_compiler, org$frostlang$frostc$ASTNode* p_m, org$frostlang$frostc$FixedArray* p_args);
org$frostlang$frostc$Pair* org$frostlang$frostc$expression$Call$possibleMatches$org$frostlang$frostc$Compiler$frost$collections$CollectionView$LTorg$frostlang$frostc$Type$GT$frost$collections$ListView$LTorg$frostlang$frostc$ASTNode$GT$org$frostlang$frostc$Compiler$TypeContext$R$org$frostlang$frostc$Pair$LTfrost$collections$CollectionView$LTorg$frostlang$frostc$Type$GT$Cfrost$core$Int$GT$Q(org$frostlang$frostc$Compiler* p_compiler, frost$collections$CollectionView* p_methodTypes, frost$collections$ListView* p_args, org$frostlang$frostc$Compiler$TypeContext* p_type);
org$frostlang$frostc$Pair* org$frostlang$frostc$expression$Call$callCost$org$frostlang$frostc$Compiler$frost$collections$CollectionView$LTorg$frostlang$frostc$Type$GT$frost$collections$ListView$LTorg$frostlang$frostc$ASTNode$GT$org$frostlang$frostc$Compiler$TypeContext$R$org$frostlang$frostc$Pair$LTorg$frostlang$frostc$Type$Cfrost$core$Int$GT$Q(org$frostlang$frostc$Compiler* p_compiler, frost$collections$CollectionView* p_methodTypes, frost$collections$ListView* p_args, org$frostlang$frostc$Compiler$TypeContext* p_type);
org$frostlang$frostc$Pair* org$frostlang$frostc$expression$Call$coercionCost$org$frostlang$frostc$Compiler$org$frostlang$frostc$ASTNode$org$frostlang$frostc$FixedArray$LTorg$frostlang$frostc$ASTNode$GT$org$frostlang$frostc$Type$R$org$frostlang$frostc$Pair$LTorg$frostlang$frostc$Type$Cfrost$core$Int$GT$Q(org$frostlang$frostc$Compiler* p_compiler, org$frostlang$frostc$ASTNode* p_m, org$frostlang$frostc$FixedArray* p_args, org$frostlang$frostc$Type* p_target);
org$frostlang$frostc$Pair* org$frostlang$frostc$expression$Call$compilePointerIntrinsic$org$frostlang$frostc$Compiler$org$frostlang$frostc$Position$org$frostlang$frostc$IR$Value$Q$org$frostlang$frostc$MethodRef$frost$collections$ListView$LTorg$frostlang$frostc$ASTNode$GT$R$org$frostlang$frostc$Pair$LTfrost$core$Bit$Corg$frostlang$frostc$IR$Value$Q$GT(org$frostlang$frostc$Compiler* p_compiler, org$frostlang$frostc$Position p_position, org$frostlang$frostc$IR$Value* p_target, org$frostlang$frostc$MethodRef* p_m, frost$collections$ListView* p_args);
org$frostlang$frostc$Pair* org$frostlang$frostc$expression$Call$compileNumberIntrinsic$org$frostlang$frostc$Compiler$org$frostlang$frostc$Position$org$frostlang$frostc$IR$Value$org$frostlang$frostc$expression$Binary$Operator$frost$collections$ListView$LTorg$frostlang$frostc$ASTNode$GT$org$frostlang$frostc$Type$org$frostlang$frostc$Type$R$org$frostlang$frostc$Pair$LTfrost$core$Bit$Corg$frostlang$frostc$IR$Value$Q$GT(org$frostlang$frostc$Compiler* p_compiler, org$frostlang$frostc$Position p_position, org$frostlang$frostc$IR$Value* p_target, org$frostlang$frostc$expression$Binary$Operator p_op, frost$collections$ListView* p_args, org$frostlang$frostc$Type* p_operandType, org$frostlang$frostc$Type* p_resultType);
org$frostlang$frostc$Pair* org$frostlang$frostc$expression$Call$compileNumberIntrinsic$org$frostlang$frostc$Compiler$org$frostlang$frostc$Position$org$frostlang$frostc$IR$Value$Q$org$frostlang$frostc$MethodRef$frost$collections$ListView$LTorg$frostlang$frostc$ASTNode$GT$R$org$frostlang$frostc$Pair$LTfrost$core$Bit$Corg$frostlang$frostc$IR$Value$Q$GT(org$frostlang$frostc$Compiler* p_compiler, org$frostlang$frostc$Position p_position, org$frostlang$frostc$IR$Value* p_target, org$frostlang$frostc$MethodRef* p_m, frost$collections$ListView* p_args);
org$frostlang$frostc$Pair* org$frostlang$frostc$expression$Call$compileBitIntrinsic$org$frostlang$frostc$Compiler$org$frostlang$frostc$Position$org$frostlang$frostc$IR$Value$Q$org$frostlang$frostc$MethodRef$frost$collections$ListView$LTorg$frostlang$frostc$ASTNode$GT$R$org$frostlang$frostc$Pair$LTfrost$core$Bit$Corg$frostlang$frostc$IR$Value$Q$GT(org$frostlang$frostc$Compiler* p_compiler, org$frostlang$frostc$Position p_position, org$frostlang$frostc$IR$Value* p_target, org$frostlang$frostc$MethodRef* p_m, frost$collections$ListView* p_args);
org$frostlang$frostc$Pair* org$frostlang$frostc$expression$Call$compileIntrinsic$org$frostlang$frostc$Compiler$org$frostlang$frostc$Position$org$frostlang$frostc$IR$Value$Q$org$frostlang$frostc$MethodRef$frost$collections$ListView$LTorg$frostlang$frostc$ASTNode$GT$R$org$frostlang$frostc$Pair$LTfrost$core$Bit$Corg$frostlang$frostc$IR$Value$Q$GT(org$frostlang$frostc$Compiler* p_compiler, org$frostlang$frostc$Position p_position, org$frostlang$frostc$IR$Value* p_target, org$frostlang$frostc$MethodRef* p_m, frost$collections$ListView* p_args);
frost$collections$ListView* org$frostlang$frostc$expression$Call$findGenericParameters$org$frostlang$frostc$MethodDecl$org$frostlang$frostc$Type$R$frost$collections$ListView$LTfrost$collections$ListView$LTfrost$core$Int$GT$GT$Q(org$frostlang$frostc$MethodDecl* p_m, org$frostlang$frostc$Type* p_t);
org$frostlang$frostc$Type* org$frostlang$frostc$expression$Call$getSubtype$org$frostlang$frostc$Type$frost$collections$ListView$LTfrost$core$Int$GT$R$org$frostlang$frostc$Type$Q(org$frostlang$frostc$Type* p_type, frost$collections$ListView* p_indices);
org$frostlang$frostc$Type* org$frostlang$frostc$expression$Call$methodRemap$org$frostlang$frostc$Compiler$org$frostlang$frostc$Type$frost$collections$HashMap$LTfrost$core$String$Corg$frostlang$frostc$Type$GT$R$org$frostlang$frostc$Type(org$frostlang$frostc$Compiler* p_compiler, org$frostlang$frostc$Type* p_type, frost$collections$HashMap* p_map);
org$frostlang$frostc$expression$Call$ImplicationsResult org$frostlang$frostc$expression$Call$determineImplications$org$frostlang$frostc$Compiler$org$frostlang$frostc$MethodDecl$org$frostlang$frostc$Type$org$frostlang$frostc$Type$frost$collections$HashMap$LTfrost$core$String$Corg$frostlang$frostc$Type$GT$R$org$frostlang$frostc$expression$Call$ImplicationsResult(org$frostlang$frostc$Compiler* p_compiler, org$frostlang$frostc$MethodDecl* p_m, org$frostlang$frostc$Type* p_src, org$frostlang$frostc$Type* p_target, frost$collections$HashMap* p_currentMapping);
org$frostlang$frostc$expression$Call$ImplicationsResult org$frostlang$frostc$expression$Call$determineImplications$org$frostlang$frostc$Compiler$org$frostlang$frostc$MethodDecl$org$frostlang$frostc$ASTNode$org$frostlang$frostc$Type$frost$collections$HashMap$LTfrost$core$String$Corg$frostlang$frostc$Type$GT$R$org$frostlang$frostc$expression$Call$ImplicationsResult(org$frostlang$frostc$Compiler* p_compiler, org$frostlang$frostc$MethodDecl* p_m, org$frostlang$frostc$ASTNode* p_src, org$frostlang$frostc$Type* p_target, frost$collections$HashMap* p_currentMapping);
org$frostlang$frostc$MethodRef* org$frostlang$frostc$expression$Call$performTypeInference$org$frostlang$frostc$Compiler$org$frostlang$frostc$MethodRef$frost$collections$ListView$LTorg$frostlang$frostc$ASTNode$GT$org$frostlang$frostc$Compiler$TypeContext$R$org$frostlang$frostc$MethodRef$Q(org$frostlang$frostc$Compiler* p_compiler, org$frostlang$frostc$MethodRef* p_m, frost$collections$ListView* p_args, org$frostlang$frostc$Compiler$TypeContext* p_type);
org$frostlang$frostc$Pair* org$frostlang$frostc$expression$Call$findBestMethod$org$frostlang$frostc$Compiler$org$frostlang$frostc$Position$org$frostlang$frostc$IR$Value$Q$frost$collections$ListView$LTorg$frostlang$frostc$MethodDecl$GT$frost$collections$ListView$LTorg$frostlang$frostc$ASTNode$GT$org$frostlang$frostc$Compiler$TypeContext$R$org$frostlang$frostc$Pair$LTfrost$collections$ListView$LTorg$frostlang$frostc$MethodRef$GT$Cfrost$core$Int$GT$Q(org$frostlang$frostc$Compiler* p_compiler, org$frostlang$frostc$Position p_position, org$frostlang$frostc$IR$Value* p_target, frost$collections$ListView* p_methods, frost$collections$ListView* p_args, org$frostlang$frostc$Compiler$TypeContext* p_type);
org$frostlang$frostc$Pair* org$frostlang$frostc$expression$Call$findBestMethod$org$frostlang$frostc$Compiler$org$frostlang$frostc$Position$org$frostlang$frostc$IR$Value$Q$frost$collections$ListView$LTorg$frostlang$frostc$MethodDecl$GT$frost$collections$ListView$LTorg$frostlang$frostc$Type$GT$Q$frost$collections$ListView$LTorg$frostlang$frostc$ASTNode$GT$org$frostlang$frostc$Compiler$TypeContext$R$org$frostlang$frostc$Pair$LTfrost$collections$ListView$LTorg$frostlang$frostc$MethodRef$GT$Cfrost$core$Int$GT$Q(org$frostlang$frostc$Compiler* p_compiler, org$frostlang$frostc$Position p_position, org$frostlang$frostc$IR$Value* p_target, frost$collections$ListView* p_methods, frost$collections$ListView* p_genericArguments, frost$collections$ListView* p_args, org$frostlang$frostc$Compiler$TypeContext* p_type);
org$frostlang$frostc$IR$Value* org$frostlang$frostc$expression$Call$callMethodObject$org$frostlang$frostc$Compiler$org$frostlang$frostc$Position$org$frostlang$frostc$IR$Value$frost$collections$ListView$LTorg$frostlang$frostc$ASTNode$GT$org$frostlang$frostc$Compiler$TypeContext$R$org$frostlang$frostc$IR$Value$Q(org$frostlang$frostc$Compiler* p_compiler, org$frostlang$frostc$Position p_position, org$frostlang$frostc$IR$Value* p_m, frost$collections$ListView* p_args, org$frostlang$frostc$Compiler$TypeContext* p_type);
org$frostlang$frostc$IR$Value* org$frostlang$frostc$expression$Call$compile$org$frostlang$frostc$Compiler$org$frostlang$frostc$Position$org$frostlang$frostc$IR$Value$frost$collections$ListView$LTorg$frostlang$frostc$ASTNode$GT$org$frostlang$frostc$Compiler$TypeContext$R$org$frostlang$frostc$IR$Value$Q(org$frostlang$frostc$Compiler* p_compiler, org$frostlang$frostc$Position p_position, org$frostlang$frostc$IR$Value* p_m, frost$collections$ListView* p_args, org$frostlang$frostc$Compiler$TypeContext* p_type);
org$frostlang$frostc$IR$Value* org$frostlang$frostc$expression$Call$handleErrors$org$frostlang$frostc$Compiler$org$frostlang$frostc$Position$org$frostlang$frostc$IR$Value$R$org$frostlang$frostc$IR$Value$Q(org$frostlang$frostc$Compiler* p_compiler, org$frostlang$frostc$Position p_position, org$frostlang$frostc$IR$Value* p_v);
frost$core$Int org$frostlang$frostc$expression$Call$countReturns$org$frostlang$frostc$ASTNode$R$frost$core$Int(org$frostlang$frostc$ASTNode* p_s);
frost$core$Int org$frostlang$frostc$expression$Call$countReturns$frost$collections$ListView$LTorg$frostlang$frostc$ASTNode$GT$R$frost$core$Int(frost$collections$ListView* p_b);
org$frostlang$frostc$IR$Value* org$frostlang$frostc$expression$Call$inlineCall$org$frostlang$frostc$Compiler$org$frostlang$frostc$Position$org$frostlang$frostc$MethodDecl$frost$collections$ListView$LTorg$frostlang$frostc$IR$Value$GT$R$org$frostlang$frostc$IR$Value$Q(org$frostlang$frostc$Compiler* p_compiler, org$frostlang$frostc$Position p_position, org$frostlang$frostc$MethodDecl* p_m, frost$collections$ListView* p_args);
org$frostlang$frostc$IR$Value* org$frostlang$frostc$expression$Call$compile$org$frostlang$frostc$Compiler$org$frostlang$frostc$Position$org$frostlang$frostc$IR$Value$Q$org$frostlang$frostc$MethodRef$frost$collections$ListView$LTorg$frostlang$frostc$ASTNode$GT$org$frostlang$frostc$Compiler$TypeContext$R$org$frostlang$frostc$IR$Value$Q(org$frostlang$frostc$Compiler* p_compiler, org$frostlang$frostc$Position p_position, org$frostlang$frostc$IR$Value* p_target, org$frostlang$frostc$MethodRef* p_rawM, frost$collections$ListView* p_args, org$frostlang$frostc$Compiler$TypeContext* p_type);
org$frostlang$frostc$IR$Value* org$frostlang$frostc$expression$Call$compile$org$frostlang$frostc$Compiler$org$frostlang$frostc$Position$org$frostlang$frostc$IR$Value$frost$core$String$frost$collections$ListView$LTorg$frostlang$frostc$ASTNode$GT$org$frostlang$frostc$Compiler$TypeContext$R$org$frostlang$frostc$IR$Value$Q(org$frostlang$frostc$Compiler* p_compiler, org$frostlang$frostc$Position p_position, org$frostlang$frostc$IR$Value* p_target, frost$core$String* p_m, frost$collections$ListView* p_args, org$frostlang$frostc$Compiler$TypeContext* p_type);
org$frostlang$frostc$IR$Value* org$frostlang$frostc$expression$Call$compile$org$frostlang$frostc$Compiler$org$frostlang$frostc$Position$org$frostlang$frostc$ASTNode$org$frostlang$frostc$FixedArray$LTorg$frostlang$frostc$ASTNode$GT$frost$core$Bit$org$frostlang$frostc$Compiler$TypeContext$R$org$frostlang$frostc$IR$Value$Q(org$frostlang$frostc$Compiler* p_compiler, org$frostlang$frostc$Position p_position, org$frostlang$frostc$ASTNode* p_m, org$frostlang$frostc$FixedArray* p_args, frost$core$Bit p_isStatement, org$frostlang$frostc$Compiler$TypeContext* p_type);
void org$frostlang$frostc$expression$Call$init(void* rawSelf);
void org$frostlang$frostc$expression$Call$cleanup(void* rawSelf);

