#pragma once
#include "frost_c.h"
#include "CCodeGenerator_types.h"
typedef struct org$frostlanguage$frostc$CCodeGenerator org$frostlanguage$frostc$CCodeGenerator;
typedef struct frost$io$File frost$io$File;
typedef struct org$frostlanguage$frostc$HCodeGenerator org$frostlanguage$frostc$HCodeGenerator;
typedef struct frost$core$String frost$core$String;
typedef struct org$frostlanguage$frostc$MethodDecl org$frostlanguage$frostc$MethodDecl;
#include "frost/core/Int64_types.h"
typedef struct org$frostlanguage$frostc$Type org$frostlanguage$frostc$Type;
#include "frost/core/Bit_types.h"
typedef struct org$frostlanguage$frostc$ClassDecl org$frostlanguage$frostc$ClassDecl;
typedef struct org$frostlanguage$frostc$Compiler org$frostlanguage$frostc$Compiler;
typedef struct org$frostlanguage$frostc$CCodeGenerator$MethodShim org$frostlanguage$frostc$CCodeGenerator$MethodShim;
typedef struct org$frostlanguage$frostc$CCodeGenerator$ClassConstant org$frostlanguage$frostc$CCodeGenerator$ClassConstant;
typedef struct org$frostlanguage$frostc$Variable org$frostlanguage$frostc$Variable;
typedef struct org$frostlanguage$frostc$FieldDecl org$frostlanguage$frostc$FieldDecl;
#include "org/frostlanguage/frostc/CCodeGenerator/OpClass_types.h"
#include "org/frostlanguage/frostc/parser/Token/Kind_types.h"
typedef struct frost$io$IndentedOutputStream frost$io$IndentedOutputStream;
#include "frost/core/UInt64_types.h"
#include "frost/core/Real64_types.h"
typedef struct org$frostlanguage$frostc$IR$Value org$frostlanguage$frostc$IR$Value;
typedef struct org$frostlanguage$frostc$ChoiceCase org$frostlanguage$frostc$ChoiceCase;
#include "org/frostlanguage/frostc/IR/Statement/ID_types.h"
#include "org/frostlanguage/frostc/IR/Block/ID_types.h"
typedef struct org$frostlanguage$frostc$FixedArray org$frostlanguage$frostc$FixedArray;
typedef struct frost$collections$ListView frost$collections$ListView;
typedef struct org$frostlanguage$frostc$IR$Statement org$frostlanguage$frostc$IR$Statement;
typedef struct org$frostlanguage$frostc$IR org$frostlanguage$frostc$IR;

void org$frostlanguage$frostc$CCodeGenerator$init$frost$io$File(org$frostlanguage$frostc$CCodeGenerator* self, frost$io$File* p_outDir);
void org$frostlanguage$frostc$CCodeGenerator$init$frost$io$File$org$frostlanguage$frostc$HCodeGenerator(org$frostlanguage$frostc$CCodeGenerator* self, frost$io$File* p_outDir, org$frostlanguage$frostc$HCodeGenerator* p_hCodeGen);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$escapeName$frost$core$String$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, frost$core$String* p_s);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$getName$org$frostlanguage$frostc$MethodDecl$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$MethodDecl* p_m);
frost$core$Int64 org$frostlanguage$frostc$CCodeGenerator$sizeOf$org$frostlanguage$frostc$Type$R$frost$core$Int64(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$Type* p_t);
frost$core$Bit org$frostlanguage$frostc$CCodeGenerator$isExternal$org$frostlanguage$frostc$ClassDecl$R$frost$core$Bit(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$ClassDecl* p_cl);
void org$frostlanguage$frostc$CCodeGenerator$writeImport$org$frostlanguage$frostc$ClassDecl(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$ClassDecl* p_cl);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$cType$org$frostlanguage$frostc$Type$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$Type* p_t);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$cMethodType$org$frostlanguage$frostc$Type$org$frostlanguage$frostc$Type$Q$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$Type* p_t, org$frostlanguage$frostc$Type* p_selfType);
void org$frostlanguage$frostc$CCodeGenerator$setCompiler$org$frostlanguage$frostc$Compiler(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$Compiler* p_compiler);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$nextVar$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$nextLabel$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self);
frost$core$Int64 org$frostlanguage$frostc$CCodeGenerator$getChoiceDataSize$org$frostlanguage$frostc$ClassDecl$R$frost$core$Int64(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$ClassDecl* p_cl);
frost$core$Int64 org$frostlanguage$frostc$CCodeGenerator$fieldSize$org$frostlanguage$frostc$Type$R$frost$core$Int64(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$Type* p_t);
frost$core$Int64 org$frostlanguage$frostc$CCodeGenerator$alignment$org$frostlanguage$frostc$Type$R$frost$core$Int64(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$Type* p_t);
frost$core$Int64 org$frostlanguage$frostc$CCodeGenerator$stride$org$frostlanguage$frostc$Type$R$frost$core$Int64(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$Type* p_t);
frost$core$Int64 org$frostlanguage$frostc$CCodeGenerator$sizeOfWrapper$org$frostlanguage$frostc$Type$R$frost$core$Int64(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$Type* p_t);
void org$frostlanguage$frostc$CCodeGenerator$writeType$org$frostlanguage$frostc$Type(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$Type* p_t);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$typeName$org$frostlanguage$frostc$Type$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$Type* p_t);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$wrapperTypeName$org$frostlanguage$frostc$Type$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$Type* p_t);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$wrapperType$org$frostlanguage$frostc$Type$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$Type* p_t);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$wrapperType$org$frostlanguage$frostc$MethodDecl$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$MethodDecl* p_m);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$nullableType$org$frostlanguage$frostc$Type$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$Type* p_t);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$getITable$org$frostlanguage$frostc$ClassDecl$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$ClassDecl* p_cl);
org$frostlanguage$frostc$CCodeGenerator$MethodShim* org$frostlanguage$frostc$CCodeGenerator$createMethodShim$org$frostlanguage$frostc$MethodDecl$org$frostlanguage$frostc$Type$R$org$frostlanguage$frostc$CCodeGenerator$MethodShim(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$MethodDecl* p_raw, org$frostlanguage$frostc$Type* p_effective);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$getWrapperITable$org$frostlanguage$frostc$ClassDecl$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$ClassDecl* p_cl);
frost$core$Bit org$frostlanguage$frostc$CCodeGenerator$needsStructIndirection$org$frostlanguage$frostc$MethodDecl$R$frost$core$Bit(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$MethodDecl* p_m);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$getMethodTableEntry$org$frostlanguage$frostc$MethodDecl$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$MethodDecl* p_m);
org$frostlanguage$frostc$CCodeGenerator$ClassConstant* org$frostlanguage$frostc$CCodeGenerator$getClassConstant$org$frostlanguage$frostc$ClassDecl$R$org$frostlanguage$frostc$CCodeGenerator$ClassConstant(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$ClassDecl* p_cl);
org$frostlanguage$frostc$CCodeGenerator$ClassConstant* org$frostlanguage$frostc$CCodeGenerator$getWrapperClassConstant$org$frostlanguage$frostc$ClassDecl$R$org$frostlanguage$frostc$CCodeGenerator$ClassConstant(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$ClassDecl* p_cl);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$getName$org$frostlanguage$frostc$Variable$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$Variable* p_v);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$getName$org$frostlanguage$frostc$FieldDecl$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$FieldDecl* p_f);
org$frostlanguage$frostc$CCodeGenerator$OpClass org$frostlanguage$frostc$CCodeGenerator$opClass$org$frostlanguage$frostc$Type$R$org$frostlanguage$frostc$CCodeGenerator$OpClass(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$Type* p_t);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$getBinaryReference$org$frostlanguage$frostc$Type$frost$core$String$org$frostlanguage$frostc$parser$Token$Kind$frost$core$String$frost$io$IndentedOutputStream$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$Type* p_t, frost$core$String* p_leftRef, org$frostlanguage$frostc$parser$Token$Kind p_op, frost$core$String* p_rightRef, frost$io$IndentedOutputStream* p_out);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$getVirtualMethodReference$frost$core$String$org$frostlanguage$frostc$MethodDecl$frost$io$IndentedOutputStream$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, frost$core$String* p_target, org$frostlanguage$frostc$MethodDecl* p_m, frost$io$IndentedOutputStream* p_out);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$getInterfaceMethodReference$frost$core$String$org$frostlanguage$frostc$MethodDecl$frost$io$IndentedOutputStream$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, frost$core$String* p_target, org$frostlanguage$frostc$MethodDecl* p_m, frost$io$IndentedOutputStream* p_out);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$getMethodReference$frost$core$String$Q$org$frostlanguage$frostc$MethodDecl$frost$core$Bit$frost$io$IndentedOutputStream$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, frost$core$String* p_target, org$frostlanguage$frostc$MethodDecl* p_m, frost$core$Bit p_isSuper, frost$io$IndentedOutputStream* p_out);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$wrapValue$frost$core$String$org$frostlanguage$frostc$Type$org$frostlanguage$frostc$Type$frost$io$IndentedOutputStream$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, frost$core$String* p_value, org$frostlanguage$frostc$Type* p_srcType, org$frostlanguage$frostc$Type* p_dstType, frost$io$IndentedOutputStream* p_out);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$unwrapValue$frost$core$String$org$frostlanguage$frostc$Type$org$frostlanguage$frostc$Type$frost$io$IndentedOutputStream$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, frost$core$String* p_value, org$frostlanguage$frostc$Type* p_srcType, org$frostlanguage$frostc$Type* p_dstType, frost$io$IndentedOutputStream* p_out);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$toNullableValue$frost$core$String$org$frostlanguage$frostc$Type$org$frostlanguage$frostc$Type$frost$io$IndentedOutputStream$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, frost$core$String* p_value, org$frostlanguage$frostc$Type* p_srcType, org$frostlanguage$frostc$Type* p_dstType, frost$io$IndentedOutputStream* p_out);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$toNonNullableValue$frost$core$String$org$frostlanguage$frostc$Type$org$frostlanguage$frostc$Type$frost$io$IndentedOutputStream$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, frost$core$String* p_value, org$frostlanguage$frostc$Type* p_srcType, org$frostlanguage$frostc$Type* p_dstType, frost$io$IndentedOutputStream* p_out);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$getCastReference$frost$core$String$org$frostlanguage$frostc$Type$org$frostlanguage$frostc$Type$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, frost$core$String* p_value, org$frostlanguage$frostc$Type* p_src, org$frostlanguage$frostc$Type* p_target);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$getIntReference$frost$core$UInt64$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, frost$core$UInt64 p_int);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$getRealReference$org$frostlanguage$frostc$Type$frost$core$Real64$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$Type* p_type, frost$core$Real64 p_real);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$getBitReference$frost$core$Bit$frost$io$IndentedOutputStream$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, frost$core$Bit p_bit, frost$io$IndentedOutputStream* p_out);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$getStringReference$frost$core$String$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, frost$core$String* p_s);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$getNullReference$org$frostlanguage$frostc$Type$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$Type* p_t);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$getReference$org$frostlanguage$frostc$IR$Value$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Value* p_v);
frost$core$Int64 org$frostlanguage$frostc$CCodeGenerator$getChoiceFieldOffset$org$frostlanguage$frostc$ChoiceCase$frost$core$Int64$R$frost$core$Int64(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$ChoiceCase* p_e, frost$core$Int64 p_index);
frost$core$String* org$frostlanguage$frostc$CCodeGenerator$selfType$org$frostlanguage$frostc$MethodDecl$R$frost$core$String(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$MethodDecl* p_m);
void org$frostlanguage$frostc$CCodeGenerator$writeIsNull$org$frostlanguage$frostc$IR$Statement$ID$org$frostlanguage$frostc$IR$Value(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Statement$ID p_id, org$frostlanguage$frostc$IR$Value* p_value);
void org$frostlanguage$frostc$CCodeGenerator$writeIsNonNull$org$frostlanguage$frostc$IR$Statement$ID$org$frostlanguage$frostc$IR$Value(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Statement$ID p_id, org$frostlanguage$frostc$IR$Value* p_value);
frost$core$Bit org$frostlanguage$frostc$CCodeGenerator$isNull$org$frostlanguage$frostc$IR$Value$R$frost$core$Bit(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Value* p_v);
void org$frostlanguage$frostc$CCodeGenerator$writeBinary$org$frostlanguage$frostc$IR$Statement$ID$org$frostlanguage$frostc$IR$Value$org$frostlanguage$frostc$parser$Token$Kind$org$frostlanguage$frostc$IR$Value$org$frostlanguage$frostc$Type(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Statement$ID p_id, org$frostlanguage$frostc$IR$Value* p_left, org$frostlanguage$frostc$parser$Token$Kind p_op, org$frostlanguage$frostc$IR$Value* p_right, org$frostlanguage$frostc$Type* p_type);
void org$frostlanguage$frostc$CCodeGenerator$writeBranch$org$frostlanguage$frostc$IR$Block$ID(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Block$ID p_target);
void org$frostlanguage$frostc$CCodeGenerator$writeCast$org$frostlanguage$frostc$IR$Statement$ID$org$frostlanguage$frostc$IR$Value$org$frostlanguage$frostc$Type(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Statement$ID p_id, org$frostlanguage$frostc$IR$Value* p_value, org$frostlanguage$frostc$Type* p_target);
void org$frostlanguage$frostc$CCodeGenerator$writeConditionalBranch$org$frostlanguage$frostc$IR$Value$org$frostlanguage$frostc$IR$Block$ID$org$frostlanguage$frostc$IR$Block$ID(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Value* p_test, org$frostlanguage$frostc$IR$Block$ID p_ifTrue, org$frostlanguage$frostc$IR$Block$ID p_ifFalse);
void org$frostlanguage$frostc$CCodeGenerator$writeConstruct$org$frostlanguage$frostc$IR$Statement$ID$org$frostlanguage$frostc$ClassDecl(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Statement$ID p_id, org$frostlanguage$frostc$ClassDecl* p_cl);
void org$frostlanguage$frostc$CCodeGenerator$writeCreateStruct$org$frostlanguage$frostc$IR$Statement$ID$org$frostlanguage$frostc$ClassDecl$org$frostlanguage$frostc$FixedArray$LTorg$frostlanguage$frostc$IR$Value$GT(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Statement$ID p_id, org$frostlanguage$frostc$ClassDecl* p_cl, org$frostlanguage$frostc$FixedArray* p_args);
void org$frostlanguage$frostc$CCodeGenerator$writeDynamicCall$org$frostlanguage$frostc$IR$Statement$ID$org$frostlanguage$frostc$IR$Value$frost$collections$ListView$LTorg$frostlanguage$frostc$IR$Value$GT(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Statement$ID p_id, org$frostlanguage$frostc$IR$Value* p_m, frost$collections$ListView* p_args);
void org$frostlanguage$frostc$CCodeGenerator$writeExtractField$org$frostlanguage$frostc$IR$Statement$ID$org$frostlanguage$frostc$IR$Value$org$frostlanguage$frostc$FieldDecl(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Statement$ID p_id, org$frostlanguage$frostc$IR$Value* p_target, org$frostlanguage$frostc$FieldDecl* p_field);
void org$frostlanguage$frostc$CCodeGenerator$writeGetChoiceFieldPointer$org$frostlanguage$frostc$IR$Statement$ID$org$frostlanguage$frostc$IR$Value$org$frostlanguage$frostc$ChoiceCase$frost$core$Int64(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Statement$ID p_id, org$frostlanguage$frostc$IR$Value* p_target, org$frostlanguage$frostc$ChoiceCase* p_cc, frost$core$Int64 p_index);
void org$frostlanguage$frostc$CCodeGenerator$writeGetFieldPointer$org$frostlanguage$frostc$IR$Statement$ID$org$frostlanguage$frostc$IR$Value$org$frostlanguage$frostc$FieldDecl(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Statement$ID p_id, org$frostlanguage$frostc$IR$Value* p_target, org$frostlanguage$frostc$FieldDecl* p_field);
void org$frostlanguage$frostc$CCodeGenerator$writeGetInterfaceMethod$org$frostlanguage$frostc$IR$Statement$ID$org$frostlanguage$frostc$IR$Value$org$frostlanguage$frostc$ClassDecl$frost$core$Int64$org$frostlanguage$frostc$Type(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Statement$ID p_id, org$frostlanguage$frostc$IR$Value* p_value, org$frostlanguage$frostc$ClassDecl* p_cl, frost$core$Int64 p_index, org$frostlanguage$frostc$Type* p_type);
void org$frostlanguage$frostc$CCodeGenerator$writeGetVirtualMethod$org$frostlanguage$frostc$IR$Statement$ID$org$frostlanguage$frostc$IR$Value$frost$core$Int64$org$frostlanguage$frostc$Type(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Statement$ID p_id, org$frostlanguage$frostc$IR$Value* p_value, frost$core$Int64 p_index, org$frostlanguage$frostc$Type* p_type);
void org$frostlanguage$frostc$CCodeGenerator$writeLoad$org$frostlanguage$frostc$IR$Statement$ID$org$frostlanguage$frostc$IR$Value(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Statement$ID p_id, org$frostlanguage$frostc$IR$Value* p_ptr);
void org$frostlanguage$frostc$CCodeGenerator$writeNegate$org$frostlanguage$frostc$IR$Statement$ID$org$frostlanguage$frostc$IR$Value(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Statement$ID p_id, org$frostlanguage$frostc$IR$Value* p_value);
void org$frostlanguage$frostc$CCodeGenerator$writeNot$org$frostlanguage$frostc$IR$Statement$ID$org$frostlanguage$frostc$IR$Value(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Statement$ID p_id, org$frostlanguage$frostc$IR$Value* p_value);
void org$frostlanguage$frostc$CCodeGenerator$writePointerAlloc$org$frostlanguage$frostc$IR$Statement$ID$org$frostlanguage$frostc$IR$Value$org$frostlanguage$frostc$Type(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Statement$ID p_id, org$frostlanguage$frostc$IR$Value* p_count, org$frostlanguage$frostc$Type* p_t);
void org$frostlanguage$frostc$CCodeGenerator$writePointerDestroy$org$frostlanguage$frostc$IR$Value(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Value* p_ptr);
void org$frostlanguage$frostc$CCodeGenerator$writePointerGetIndex$org$frostlanguage$frostc$IR$Statement$ID$org$frostlanguage$frostc$IR$Value$org$frostlanguage$frostc$IR$Value(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Statement$ID p_id, org$frostlanguage$frostc$IR$Value* p_ptr, org$frostlanguage$frostc$IR$Value* p_index);
void org$frostlanguage$frostc$CCodeGenerator$writePointerOffset$org$frostlanguage$frostc$IR$Statement$ID$org$frostlanguage$frostc$IR$Value$org$frostlanguage$frostc$IR$Value(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Statement$ID p_id, org$frostlanguage$frostc$IR$Value* p_ptr, org$frostlanguage$frostc$IR$Value* p_offset);
void org$frostlanguage$frostc$CCodeGenerator$writePointerRealloc$org$frostlanguage$frostc$IR$Statement$ID$org$frostlanguage$frostc$IR$Value$org$frostlanguage$frostc$IR$Value$org$frostlanguage$frostc$IR$Value(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Statement$ID p_id, org$frostlanguage$frostc$IR$Value* p_ptr, org$frostlanguage$frostc$IR$Value* p_oldCount, org$frostlanguage$frostc$IR$Value* p_newCount);
void org$frostlanguage$frostc$CCodeGenerator$writePointerSetIndex$org$frostlanguage$frostc$IR$Value$org$frostlanguage$frostc$IR$Value$org$frostlanguage$frostc$IR$Value(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Value* p_value, org$frostlanguage$frostc$IR$Value* p_ptr, org$frostlanguage$frostc$IR$Value* p_index);
void org$frostlanguage$frostc$CCodeGenerator$writeReturn$org$frostlanguage$frostc$IR$Value$Q(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Value* p_value);
void org$frostlanguage$frostc$CCodeGenerator$writeStaticCall$org$frostlanguage$frostc$IR$Statement$ID$org$frostlanguage$frostc$MethodDecl$frost$collections$ListView$LTorg$frostlanguage$frostc$IR$Value$GT(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Statement$ID p_id, org$frostlanguage$frostc$MethodDecl* p_m, frost$collections$ListView* p_args);
void org$frostlanguage$frostc$CCodeGenerator$writeStore$org$frostlanguage$frostc$IR$Value$org$frostlanguage$frostc$IR$Value(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Value* p_value, org$frostlanguage$frostc$IR$Value* p_ptr);
void org$frostlanguage$frostc$CCodeGenerator$writeStatement$org$frostlanguage$frostc$IR$Statement$ID$org$frostlanguage$frostc$IR$Statement(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR$Statement$ID p_id, org$frostlanguage$frostc$IR$Statement* p_s);
void org$frostlanguage$frostc$CCodeGenerator$writeDeclaration$org$frostlanguage$frostc$MethodDecl(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$MethodDecl* p_m);
void org$frostlanguage$frostc$CCodeGenerator$writeIR$org$frostlanguage$frostc$IR(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$IR* p_ir);
void org$frostlanguage$frostc$CCodeGenerator$write$org$frostlanguage$frostc$MethodDecl$org$frostlanguage$frostc$IR(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$MethodDecl* p_m, org$frostlanguage$frostc$IR* p_ir);
void org$frostlanguage$frostc$CCodeGenerator$start$org$frostlanguage$frostc$ClassDecl(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$ClassDecl* p_cl);
void org$frostlanguage$frostc$CCodeGenerator$end$org$frostlanguage$frostc$ClassDecl(org$frostlanguage$frostc$CCodeGenerator* self, org$frostlanguage$frostc$ClassDecl* p_cl);
void org$frostlanguage$frostc$CCodeGenerator$finish(org$frostlanguage$frostc$CCodeGenerator* self);
void org$frostlanguage$frostc$CCodeGenerator$cleanup(org$frostlanguage$frostc$CCodeGenerator* self);

