#pragma once
#include "frost_c.h"
#include "Statement_types.h"
#include "org/frostlang/frostc/MethodPosition_types.h"
typedef struct org$frostlang$frostc$Code$Statement org$frostlang$frostc$Code$Statement;
#include "frost/core/Int_types.h"
#include "org/frostlang/frostc/Code/Statement/ID_types.h"
typedef struct org$frostlang$frostc$Code$Value org$frostlang$frostc$Code$Value;
typedef struct org$frostlang$frostc$Code$PrimitiveType org$frostlang$frostc$Code$PrimitiveType;
#include "org/frostlang/frostc/Code/Block/ID_types.h"
typedef struct frost$core$String frost$core$String;
typedef struct org$frostlang$frostc$FixedArray org$frostlang$frostc$FixedArray;
typedef struct org$frostlang$frostc$Code$Signature org$frostlang$frostc$Code$Signature;

org$frostlang$frostc$MethodPosition org$frostlang$frostc$Code$Statement$get_position$R$org$frostlang$frostc$MethodPosition(void* rawSelf);
void org$frostlang$frostc$Code$Statement$cleanup(void* rawSelf);
void org$frostlang$frostc$Code$Statement$init$frost$core$Int$org$frostlang$frostc$MethodPosition$org$frostlang$frostc$Code$Statement$ID$org$frostlang$frostc$Code$Value$org$frostlang$frostc$Code$Value(void* rawSelf, frost$core$Int p_rv, org$frostlang$frostc$MethodPosition p_f0, org$frostlang$frostc$Code$Statement$ID p_f1, org$frostlang$frostc$Code$Value* p_f2, org$frostlang$frostc$Code$Value* p_f3);
void org$frostlang$frostc$Code$Statement$init$frost$core$Int$org$frostlang$frostc$MethodPosition$org$frostlang$frostc$Code$Statement$ID$org$frostlang$frostc$Code$Value$org$frostlang$frostc$Code$PrimitiveType(void* rawSelf, frost$core$Int p_rv, org$frostlang$frostc$MethodPosition p_f0, org$frostlang$frostc$Code$Statement$ID p_f1, org$frostlang$frostc$Code$Value* p_f2, org$frostlang$frostc$Code$PrimitiveType* p_f3);
void org$frostlang$frostc$Code$Statement$init$frost$core$Int$org$frostlang$frostc$MethodPosition$org$frostlang$frostc$Code$Block$ID(void* rawSelf, frost$core$Int p_rv, org$frostlang$frostc$MethodPosition p_f0, org$frostlang$frostc$Code$Block$ID p_f1);
void org$frostlang$frostc$Code$Statement$init$frost$core$Int$org$frostlang$frostc$MethodPosition$org$frostlang$frostc$Code$Value$org$frostlang$frostc$Code$Block$ID$org$frostlang$frostc$Code$Block$ID(void* rawSelf, frost$core$Int p_rv, org$frostlang$frostc$MethodPosition p_f0, org$frostlang$frostc$Code$Value* p_f1, org$frostlang$frostc$Code$Block$ID p_f2, org$frostlang$frostc$Code$Block$ID p_f3);
void org$frostlang$frostc$Code$Statement$init$frost$core$Int$org$frostlang$frostc$MethodPosition$frost$core$String(void* rawSelf, frost$core$Int p_rv, org$frostlang$frostc$MethodPosition p_f0, frost$core$String* p_f1);
void org$frostlang$frostc$Code$Statement$init$frost$core$Int$org$frostlang$frostc$MethodPosition$org$frostlang$frostc$Code$Statement$ID$org$frostlang$frostc$Code$PrimitiveType$org$frostlang$frostc$Code$Value(void* rawSelf, frost$core$Int p_rv, org$frostlang$frostc$MethodPosition p_f0, org$frostlang$frostc$Code$Statement$ID p_f1, org$frostlang$frostc$Code$PrimitiveType* p_f2, org$frostlang$frostc$Code$Value* p_f3);
void org$frostlang$frostc$Code$Statement$init$frost$core$Int$org$frostlang$frostc$MethodPosition$org$frostlang$frostc$Code$Statement$ID$org$frostlang$frostc$Code$PrimitiveType(void* rawSelf, frost$core$Int p_rv, org$frostlang$frostc$MethodPosition p_f0, org$frostlang$frostc$Code$Statement$ID p_f1, org$frostlang$frostc$Code$PrimitiveType* p_f2);
void org$frostlang$frostc$Code$Statement$init$frost$core$Int$org$frostlang$frostc$MethodPosition$org$frostlang$frostc$Code$Statement$ID$org$frostlang$frostc$Code$PrimitiveType$org$frostlang$frostc$FixedArray$LTorg$frostlang$frostc$Code$Value$GT(void* rawSelf, frost$core$Int p_rv, org$frostlang$frostc$MethodPosition p_f0, org$frostlang$frostc$Code$Statement$ID p_f1, org$frostlang$frostc$Code$PrimitiveType* p_f2, org$frostlang$frostc$FixedArray* p_f3);
void org$frostlang$frostc$Code$Statement$init$frost$core$Int$org$frostlang$frostc$MethodPosition$org$frostlang$frostc$Code$Statement$ID$org$frostlang$frostc$Code$PrimitiveType$org$frostlang$frostc$Code$Value$org$frostlang$frostc$FixedArray$LTorg$frostlang$frostc$Code$Value$GT(void* rawSelf, frost$core$Int p_rv, org$frostlang$frostc$MethodPosition p_f0, org$frostlang$frostc$Code$Statement$ID p_f1, org$frostlang$frostc$Code$PrimitiveType* p_f2, org$frostlang$frostc$Code$Value* p_f3, org$frostlang$frostc$FixedArray* p_f4);
void org$frostlang$frostc$Code$Statement$init$frost$core$Int$org$frostlang$frostc$MethodPosition$org$frostlang$frostc$Code$Value$org$frostlang$frostc$FixedArray$LTorg$frostlang$frostc$Code$Value$GT(void* rawSelf, frost$core$Int p_rv, org$frostlang$frostc$MethodPosition p_f0, org$frostlang$frostc$Code$Value* p_f1, org$frostlang$frostc$FixedArray* p_f2);
void org$frostlang$frostc$Code$Statement$init$frost$core$Int$org$frostlang$frostc$MethodPosition$org$frostlang$frostc$Code$Statement$ID$org$frostlang$frostc$Code$Value$frost$core$Int(void* rawSelf, frost$core$Int p_rv, org$frostlang$frostc$MethodPosition p_f0, org$frostlang$frostc$Code$Statement$ID p_f1, org$frostlang$frostc$Code$Value* p_f2, frost$core$Int p_f3);
void org$frostlang$frostc$Code$Statement$init$frost$core$Int$org$frostlang$frostc$MethodPosition$org$frostlang$frostc$Code$Value$org$frostlang$frostc$Code$Value(void* rawSelf, frost$core$Int p_rv, org$frostlang$frostc$MethodPosition p_f0, org$frostlang$frostc$Code$Value* p_f1, org$frostlang$frostc$Code$Value* p_f2);
void org$frostlang$frostc$Code$Statement$init$frost$core$Int$org$frostlang$frostc$MethodPosition$org$frostlang$frostc$Code$Statement$ID$org$frostlang$frostc$Code$Value(void* rawSelf, frost$core$Int p_rv, org$frostlang$frostc$MethodPosition p_f0, org$frostlang$frostc$Code$Statement$ID p_f1, org$frostlang$frostc$Code$Value* p_f2);
void org$frostlang$frostc$Code$Statement$init$frost$core$Int$org$frostlang$frostc$MethodPosition$org$frostlang$frostc$Code$Value$Q(void* rawSelf, frost$core$Int p_rv, org$frostlang$frostc$MethodPosition p_f0, org$frostlang$frostc$Code$Value* p_f1);
void org$frostlang$frostc$Code$Statement$init$frost$core$Int$org$frostlang$frostc$MethodPosition$org$frostlang$frostc$Code$Statement$ID$org$frostlang$frostc$Code$Signature$org$frostlang$frostc$FixedArray$LTorg$frostlang$frostc$Code$Value$GT(void* rawSelf, frost$core$Int p_rv, org$frostlang$frostc$MethodPosition p_f0, org$frostlang$frostc$Code$Statement$ID p_f1, org$frostlang$frostc$Code$Signature* p_f2, org$frostlang$frostc$FixedArray* p_f3);
void org$frostlang$frostc$Code$Statement$init$frost$core$Int$org$frostlang$frostc$MethodPosition$org$frostlang$frostc$Code$Signature$org$frostlang$frostc$FixedArray$LTorg$frostlang$frostc$Code$Value$GT(void* rawSelf, frost$core$Int p_rv, org$frostlang$frostc$MethodPosition p_f0, org$frostlang$frostc$Code$Signature* p_f1, org$frostlang$frostc$FixedArray* p_f2);
void org$frostlang$frostc$Code$Statement$init$frost$core$Int$org$frostlang$frostc$MethodPosition(void* rawSelf, frost$core$Int p_rv, org$frostlang$frostc$MethodPosition p_f0);
frost$core$String* org$frostlang$frostc$Code$Statement$get_asString$R$frost$core$String(void* rawSelf);

